# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utils/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 438)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.move_left_button = QtWidgets.QPushButton(Form)
        self.move_left_button.setText("")
        icon = QtGui.QIcon.fromTheme("back")
        self.move_left_button.setIcon(icon)
        self.move_left_button.setObjectName("move_left_button")
        self.gridLayout.addWidget(self.move_left_button, 4, 1, 1, 1)
        self.zoom_out_button = QtWidgets.QPushButton(Form)
        self.zoom_out_button.setText("")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.zoom_out_button.setIcon(icon)
        self.zoom_out_button.setObjectName("zoom_out_button")
        self.gridLayout.addWidget(self.zoom_out_button, 5, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tilt_x_plus_button = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("object-flip-vertical")
        self.tilt_x_plus_button.setIcon(icon)
        self.tilt_x_plus_button.setObjectName("tilt_x_plus_button")
        self.horizontalLayout.addWidget(self.tilt_x_plus_button)
        self.tilt_x_minus_button = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("object-flip-vertical")
        self.tilt_x_minus_button.setIcon(icon)
        self.tilt_x_minus_button.setObjectName("tilt_x_minus_button")
        self.horizontalLayout.addWidget(self.tilt_x_minus_button)
        self.tilt_y_plus_button = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("object-flip-horizontal")
        self.tilt_y_plus_button.setIcon(icon)
        self.tilt_y_plus_button.setObjectName("tilt_y_plus_button")
        self.horizontalLayout.addWidget(self.tilt_y_plus_button)
        self.tilt_y_minus_button = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("object-flip-horizontal")
        self.tilt_y_minus_button.setIcon(icon)
        self.tilt_y_minus_button.setObjectName("tilt_y_minus_button")
        self.horizontalLayout.addWidget(self.tilt_y_minus_button)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 3)
        self.move_up_button = QtWidgets.QPushButton(Form)
        self.move_up_button.setText("")
        icon = QtGui.QIcon.fromTheme("up")
        self.move_up_button.setIcon(icon)
        self.move_up_button.setObjectName("move_up_button")
        self.gridLayout.addWidget(self.move_up_button, 3, 2, 1, 1)
        self.zoom_in_button = QtWidgets.QPushButton(Form)
        self.zoom_in_button.setText("")
        icon = QtGui.QIcon.fromTheme("zoom-in")
        self.zoom_in_button.setIcon(icon)
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.gridLayout.addWidget(self.zoom_in_button, 5, 1, 1, 1)
        self.rotate_right_button = QtWidgets.QPushButton(Form)
        self.rotate_right_button.setText("")
        icon = QtGui.QIcon.fromTheme("object-rotate-left")
        self.rotate_right_button.setIcon(icon)
        self.rotate_right_button.setObjectName("rotate_right_button")
        self.gridLayout.addWidget(self.rotate_right_button, 3, 3, 1, 1)
        self.move_down_button = QtWidgets.QPushButton(Form)
        self.move_down_button.setText("")
        icon = QtGui.QIcon.fromTheme("down")
        self.move_down_button.setIcon(icon)
        self.move_down_button.setObjectName("move_down_button")
        self.gridLayout.addWidget(self.move_down_button, 5, 2, 1, 1)
        self.rotate_left_button = QtWidgets.QPushButton(Form)
        self.rotate_left_button.setText("")
        icon = QtGui.QIcon.fromTheme("object-rotate-right")
        self.rotate_left_button.setIcon(icon)
        self.rotate_left_button.setObjectName("rotate_left_button")
        self.gridLayout.addWidget(self.rotate_left_button, 3, 1, 1, 1)
        self.move_right_button = QtWidgets.QPushButton(Form)
        self.move_right_button.setText("")
        icon = QtGui.QIcon.fromTheme("next")
        self.move_right_button.setIcon(icon)
        self.move_right_button.setObjectName("move_right_button")
        self.gridLayout.addWidget(self.move_right_button, 4, 3, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.get_error_button = QtWidgets.QPushButton(Form)
        self.get_error_button.setObjectName("get_error_button")
        self.gridLayout_2.addWidget(self.get_error_button, 2, 0, 1, 1)
        self.Z_label = QtWidgets.QLabel(Form)
        self.Z_label.setText("")
        self.Z_label.setObjectName("Z_label")
        self.gridLayout_2.addWidget(self.Z_label, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.roll_label = QtWidgets.QLabel(Form)
        self.roll_label.setText("")
        self.roll_label.setObjectName("roll_label")
        self.gridLayout_2.addWidget(self.roll_label, 1, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 3, 1, 1)
        self.X_label = QtWidgets.QLabel(Form)
        self.X_label.setText("")
        self.X_label.setObjectName("X_label")
        self.gridLayout_2.addWidget(self.X_label, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.get_pose_button = QtWidgets.QPushButton(Form)
        self.get_pose_button.setObjectName("get_pose_button")
        self.gridLayout_2.addWidget(self.get_pose_button, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.Y_label = QtWidgets.QLabel(Form)
        self.Y_label.setText("")
        self.Y_label.setObjectName("Y_label")
        self.gridLayout_2.addWidget(self.Y_label, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.yaw_label = QtWidgets.QLabel(Form)
        self.yaw_label.setText("")
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_2.addWidget(self.yaw_label, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.pitch_label = QtWidgets.QLabel(Form)
        self.pitch_label.setText("")
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_2.addWidget(self.pitch_label, 1, 5, 1, 1)
        self.an_error_label = QtWidgets.QLabel(Form)
        self.an_error_label.setText("")
        self.an_error_label.setObjectName("an_error_label")
        self.gridLayout_2.addWidget(self.an_error_label, 3, 1, 1, 1)
        self.xn_error_label = QtWidgets.QLabel(Form)
        self.xn_error_label.setText("")
        self.xn_error_label.setObjectName("xn_error_label")
        self.gridLayout_2.addWidget(self.xn_error_label, 3, 2, 1, 1)
        self.yn_error_label = QtWidgets.QLabel(Form)
        self.yn_error_label.setText("")
        self.yn_error_label.setObjectName("yn_error_label")
        self.gridLayout_2.addWidget(self.yn_error_label, 3, 3, 1, 1)
        self.s4_error_label = QtWidgets.QLabel(Form)
        self.s4_error_label.setText("")
        self.s4_error_label.setObjectName("s4_error_label")
        self.gridLayout_2.addWidget(self.s4_error_label, 3, 4, 1, 1)
        self.s5_error_label = QtWidgets.QLabel(Form)
        self.s5_error_label.setText("")
        self.s5_error_label.setObjectName("s5_error_label")
        self.gridLayout_2.addWidget(self.s5_error_label, 3, 5, 1, 1)
        self.theta_error_label = QtWidgets.QLabel(Form)
        self.theta_error_label.setText("")
        self.theta_error_label.setObjectName("theta_error_label")
        self.gridLayout_2.addWidget(self.theta_error_label, 3, 6, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 8, 1, 1, 5)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 5, 1, 1)
        self.camera_view = QtWidgets.QLabel(Form)
        self.camera_view.setObjectName("camera_view")
        self.gridLayout.addWidget(self.camera_view, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 5, 1, 1)
        self.angle_delta_spinbox = QtWidgets.QDoubleSpinBox(Form)
        self.angle_delta_spinbox.setMaximum(90.0)
        self.angle_delta_spinbox.setProperty("value", 5.0)
        self.angle_delta_spinbox.setObjectName("angle_delta_spinbox")
        self.gridLayout.addWidget(self.angle_delta_spinbox, 7, 4, 1, 1)
        self.shift_delta_spinbox = QtWidgets.QDoubleSpinBox(Form)
        self.shift_delta_spinbox.setMaximum(100.0)
        self.shift_delta_spinbox.setProperty("value", 10.0)
        self.shift_delta_spinbox.setObjectName("shift_delta_spinbox")
        self.gridLayout.addWidget(self.shift_delta_spinbox, 6, 4, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 6, 7, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-home")
        self.home_button.setIcon(icon)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.work_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_button.sizePolicy().hasHeightForWidth())
        self.work_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-jump")
        self.work_button.setIcon(icon)
        self.work_button.setObjectName("work_button")
        self.verticalLayout.addWidget(self.work_button)
        self.place_position_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_position_button.sizePolicy().hasHeightForWidth())
        self.place_position_button.setSizePolicy(sizePolicy)
        self.place_position_button.setObjectName("place_position_button")
        self.verticalLayout.addWidget(self.place_position_button)
        self.set_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_button.sizePolicy().hasHeightForWidth())
        self.set_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("document-save-symbolic")
        self.set_button.setIcon(icon)
        self.set_button.setObjectName("set_button")
        self.verticalLayout.addWidget(self.set_button)
        self.trace_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trace_button.sizePolicy().hasHeightForWidth())
        self.trace_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.trace_button.setIcon(icon)
        self.trace_button.setObjectName("trace_button")
        self.verticalLayout.addWidget(self.trace_button)
        self.stop_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stop_button.setIcon(icon)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        self.pick_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pick_button.sizePolicy().hasHeightForWidth())
        self.pick_button.setSizePolicy(sizePolicy)
        self.pick_button.setObjectName("pick_button")
        self.verticalLayout.addWidget(self.pick_button)
        self.place_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.place_button.sizePolicy().hasHeightForWidth())
        self.place_button.setSizePolicy(sizePolicy)
        self.place_button.setObjectName("place_button")
        self.verticalLayout.addWidget(self.place_button)
        self.release_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_button.sizePolicy().hasHeightForWidth())
        self.release_button.setSizePolicy(sizePolicy)
        self.release_button.setObjectName("release_button")
        self.verticalLayout.addWidget(self.release_button)
        self.gridLayout.addLayout(self.verticalLayout, 2, 4, 4, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 3)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 7, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.move_left_button.setToolTip(_translate("Form", "<html><head/><body><p>Shift camera view to the left.</p></body></html>"))
        self.zoom_out_button.setToolTip(_translate("Form", "<html><head/><body><p>Zoom out.</p></body></html>"))
        self.tilt_x_plus_button.setToolTip(_translate("Form", "<html><head/><body><p>Tilt camera view about x axis of camera in positive direction.</p></body></html>"))
        self.tilt_x_plus_button.setText(_translate("Form", "+"))
        self.tilt_x_minus_button.setToolTip(_translate("Form", "<html><head/><body><p>Tilt camera view about x axis of camera in negative direction.</p></body></html>"))
        self.tilt_x_minus_button.setText(_translate("Form", "-"))
        self.tilt_y_plus_button.setToolTip(_translate("Form", "<html><head/><body><p>Tilt camera view about y axis of camera in positive direction.</p></body></html>"))
        self.tilt_y_plus_button.setText(_translate("Form", "+"))
        self.tilt_y_minus_button.setToolTip(_translate("Form", "<html><head/><body><p>Tilt camera view about y axis of camera in negative direction.</p></body></html>"))
        self.tilt_y_minus_button.setText(_translate("Form", "-"))
        self.move_up_button.setToolTip(_translate("Form", "<html><head/><body><p>Shift camera view up.</p></body></html>"))
        self.zoom_in_button.setToolTip(_translate("Form", "<html><head/><body><p>Zoom in.</p></body></html>"))
        self.rotate_right_button.setToolTip(_translate("Form", "<html><head/><body><p>Rotate camera view counter-clockwise.</p></body></html>"))
        self.move_down_button.setToolTip(_translate("Form", "<html><head/><body><p>Shift camera view down.</p></body></html>"))
        self.rotate_left_button.setToolTip(_translate("Form", "<html><head/><body><p>Rotate camera view clockwise.</p></body></html>"))
        self.move_right_button.setToolTip(_translate("Form", "<html><head/><body><p>Shift camera view to the right.</p></body></html>"))
        self.get_error_button.setText(_translate("Form", "Get error"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p>a<span style=\" vertical-align:sub;\">n</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p>x<span style=\" vertical-align:sub;\">n</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "yaw"))
        self.label_5.setText(_translate("Form", "Z"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p>s<span style=\" vertical-align:sub;\">5</span></p></body></html>"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">n</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-family:\'arial,sans-serif\'; font-size:small; color:#545454; background-color:#ffffff;\">θ</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p>s<span style=\" vertical-align:sub;\">4</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "pitch"))
        self.get_pose_button.setToolTip(_translate("Form", "<html><head/><body><p>Get current robot pose.</p></body></html>"))
        self.get_pose_button.setText(_translate("Form", "Get pose"))
        self.label_6.setText(_translate("Form", "roll"))
        self.label_3.setText(_translate("Form", "X"))
        self.label_4.setText(_translate("Form", "Y"))
        self.label.setText(_translate("Form", "Δx"))
        self.camera_view.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "Δθ"))
        self.angle_delta_spinbox.setToolTip(_translate("Form", "<html><head/><body><p>Angle shift amount in degree.</p></body></html>"))
        self.shift_delta_spinbox.setToolTip(_translate("Form", "<html><head/><body><p>Shift amount in milimeter.</p></body></html>"))
        self.home_button.setToolTip(_translate("Form", "<html><head/><body><p>Go to home position.</p></body></html>"))
        self.home_button.setText(_translate("Form", "Home"))
        self.work_button.setToolTip(_translate("Form", "<html><head/><body><p>Go to workspace.</p></body></html>"))
        self.work_button.setText(_translate("Form", "Work"))
        self.place_position_button.setText(_translate("Form", "Place position"))
        self.set_button.setToolTip(_translate("Form", "<html><head/><body><p>Set current view as reference.</p></body></html>"))
        self.set_button.setText(_translate("Form", "Set"))
        self.trace_button.setToolTip(_translate("Form", "<html><head/><body><p>Run image-moment-based visual servoing.</p></body></html>"))
        self.trace_button.setText(_translate("Form", "Trace"))
        self.stop_button.setText(_translate("Form", "Stop"))
        self.pick_button.setText(_translate("Form", "Pick"))
        self.place_button.setText(_translate("Form", "Place"))
        self.release_button.setText(_translate("Form", "Release"))
        self.radioButton.setToolTip(_translate("Form", "<html><head/><body><p>Color image.</p></body></html>"))
        self.radioButton.setText(_translate("Form", "Normal"))
        self.radioButton_2.setToolTip(_translate("Form", "<html><head/><body><p>Black white image.</p></body></html>"))
        self.radioButton_2.setText(_translate("Form", "Threshold"))
        self.radioButton_3.setToolTip(_translate("Form", "<html><head/><body><p>Current frame compare to reference.</p></body></html>"))
        self.radioButton_3.setText(_translate("Form", "Compare"))
        self.comboBox.setItemText(0, _translate("Form", "blue"))
        self.comboBox.setItemText(1, _translate("Form", "green"))


